# permissions for end users to edit amfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amf-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - amfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - amfs/status
  verbs:
  - get
