# permissions for end users to view amfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: amf-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - amfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - amfs/status
  verbs:
  - get
