# permissions for end users to edit ausfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ausf-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - ausfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - ausfs/status
  verbs:
  - get
