# permissions for end users to view ausfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ausf-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - ausfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - ausfs/status
  verbs:
  - get
