# permissions for end users to edit nrves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nrf-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - nrves
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - nrves/status
  verbs:
  - get
