# permissions for end users to view nrves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nrf-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - nrves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - nrves/status
  verbs:
  - get
