# permissions for end users to view nssfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nssf-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - nssfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - nssfs/status
  verbs:
  - get
