# permissions for end users to edit pcfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pcf-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - pcfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - pcfs/status
  verbs:
  - get
