# permissions for end users to view pcfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pcf-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - pcfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - pcfs/status
  verbs:
  - get
