# permissions for end users to edit smfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smf-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - smfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - smfs/status
  verbs:
  - get
