# permissions for end users to view smfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smf-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - smfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - smfs/status
  verbs:
  - get
