# permissions for end users to edit transitions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: transition-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - transitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - transitions/status
  verbs:
  - get
