# permissions for end users to edit udrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udr-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - udrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - udrs/status
  verbs:
  - get
