# permissions for end users to view udrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: udr-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - udrs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - udrs/status
  verbs:
  - get
