# permissions for end users to edit upfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: upf-editor-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - upfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - upfs/status
  verbs:
  - get
