# permissions for end users to view webconsoles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webconsole-viewer-role
rules:
- apiGroups:
  - 5g.ibm.com
  resources:
  - webconsoles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - 5g.ibm.com
  resources:
  - webconsoles/status
  verbs:
  - get
