apiVersion: 5g.ibm.com/v1alpha1
kind: Nrf
metadata:
  name: {{ system_properties.resourceSubdomain }}  
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: {{ registry_ip }}:{{ registry_port }}/nf_nrf:latest
    mnc: "{{ mnc }}"
    mcc: "{{ mcc }}"
    mongo_ip_address: {{ mongo_ip_address }}
    port: "8000"
