apiVersion: 5g.ibm.com/v1alpha1
kind: Pcf
metadata:
  name: {{ system_properties.resourceSubdomain }}
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: "{{ registry_ip }}:{{ registry_port }}/nf_pcf:latest"
    mongo_ip_address: "{{ mongo_ip_address }}"
    nrf_ip_address: "{{ nrf_ip_address }}"
    nrf_port: "{{ nrf_port }}"
