apiVersion: 5g.ibm.com/v1alpha1
kind: Mongo
metadata:
  name: mongo-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "400Mi"
          cpu: "0.2"
        limits:
          memory: "400Mi"
          cpu: "0.2"
    image: artifactory.haifa.ibm.com:5130/weit/mongo
    image_init: artifactory.haifa.ibm.com:5130/weit/5ginitcontainer
