apiVersion: 5g.ibm.com/v1alpha1
kind: Webconsole
metadata:
  name: webconsole-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/free5gc-webui:v3.0.6
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    # TODO: define node_port here
    mongo_ip_address: "mongo-sample-sbi"
