apiVersion: 5g.ibm.com/v1alpha1
kind: Udr
metadata:
  name: udr-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/free5gc-udr:v3.1.1
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    # TODO: udr_name assumed same value as name
    udr_name: udr-sample
    nrf_ip_address: "nrf-sample-sbi"
    mongo_ip_address: "mongo-sample-sbi"
    nrf_port: "8000"
