apiVersion: 5g.ibm.com/v1alpha1
kind: Pcf
metadata:
  name: pcf-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/free5gc-pcf:v3.0.6
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    # TODO: nssf_name assumed same value as name
    pcf_name: pcf-sample
    nrf_ip_address: "nrf-sample-sbi"
    nrf_port: "8000"
    mongo_ip_address: "mongo-sample-sbi"    
