apiVersion: 5g.ibm.com/v1alpha1
kind: Nssf
metadata:
  name: nssf-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/free5gc-nssf:v3.1.1-tls
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    # TODO: nssf_name assumed same value as name
    nssf_name: nssf-sample
    nrf_ip_address: "nrf-sample-sbi"
    nrf_port: "8000"
    mnc: "93"
    mcc: "208"