apiVersion: 5g.ibm.com/v1alpha1
kind: Mongo
metadata:
  name: mongo-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "400Mi"
          cpu: "0.2"
        limits:
          memory: "400Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/mongo
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
