apiVersion: 5g.ibm.com/v1alpha1
kind: Ausf
metadata:
  name: ausf-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/free5gc-ausf:v3.0.6
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    # TODO: ausf_name assumed same value as name
    ausf_name: ausf-sample
    nrf_ip_address: "nrf-sample-sbi"
    nrf_port: "8000"
