apiVersion: 5g.ibm.com/v1alpha1
kind: Udm
metadata:
  name: udm-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/free5gc-udm:v3.1.1-tls
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    # TODO: udm_name assumed same value as name
    udm_name: udm-sample
    nrf_ip_address: "nrf-sample-sbi"
