apiVersion: 5g.ibm.com/v1alpha1
kind: Upf
metadata:
  name: upf1-sample
spec:
  config:
    image: artifactory.haifa.ibm.com:5130/weit/free5gc-upf-tools
    image_init: artifactory.haifa.ibm.com:5130/weit/5ginitcontainer
    upf_name: upf1-sample
    dnns:
    - dnn_name: internet
      apn_cidr: "60.60.0.0/16"
    - dnn_name: internet
      apn_cidr: "10.10.0.0/16"
