apiVersion: 5g.ibm.com/v1alpha1
kind: Upf
metadata:
  name: upf2-sample
spec:
  config:
    image: 172.15.0.167:5000/weit/free5gc-upf:v3.1.1-tls
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    upf_name: upf2-sample
    data_network_name: gilan
    dnns:
    - dnn_name: internet
      apn_cidr: "60.60.0.0/16"
    - dnn_name: internet
      apn_cidr: "10.10.0.0/16"
