apiVersion: 5g.ibm.com/v1alpha1
kind: Nrf
metadata:
  name: nrf-sample
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "200Mi"
          cpu: "0.2"
        limits:
          memory: "200Mi"
          cpu: "0.2"
    image: 172.15.0.167:5000/weit/free5gc-nrf:v3.1.1
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    # TODO: nrf_name assumed same value as name
    nrf_name: nrf-sample
    mnc: "93"
    mcc: "208"
    mongo_ip_address: "mongo-sample-sbi"
    port: "8000"