apiVersion: 5g.ibm.com/v1alpha1
kind: Smf
metadata:
  name: smf-sample
spec:
  config:
    image: 172.15.0.167:5000/weit/free5gc-smf:v3.0.6
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    smf_name: smf-sample
    nrf_ip_address: "nrf-sample-sbi"
    nrf_port: "8000"
    up_nodes:
    - name: gNB
      type: AN
      an_ip: 172.15.0.211
