apiVersion: 5g.ibm.com/v1alpha1
kind: Smf
metadata:
  name: smf-sample
spec:
  config:
    image: 172.15.0.167:5000/weit/free5gc-smf:1399ff7-tls
    image_init: 172.15.0.167:5000/weit/5ginitcontainer
    image_ext: 172.15.0.167:5000/weit/free5gc-smf-ext:1399ff7-tls
    smf_name: smf-sample
    nrf_ip_address: "nrf-sample-sbi"
    nrf_port: "8000"
    up_nodes:
    - name: gNB1
      type: AN
      nrCellId: "000000010"
    - name: gNB2
      type: AN
      nrCellId: "000000020"
      
