---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sbi
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "sbi",
            "type": "macvlan",
            "master": "ens160",
            "ipam": {
              "type": "whereabouts",
              "datastore": "kubernetes",
              "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
              "range": "10.100.200.0/24",
              "range_start": "10.100.200.2",
              "range_end": "10.100.200.50",
              "log_file" : "/tmp/whereabouts.log",
              "log_level" : "debug"
            },
            "gateway": "",
            "mtu": 1450
        }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ngap
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "ngap",
            "type": "macvlan",
            "master": "ens160",
            "ipam": {
              "type": "whereabouts",
              "datastore": "kubernetes",
              "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
              "range": "172.15.0.0/24",
              "range_start": "172.15.0.2",
              "range_end": "172.15.0.10",
              "log_file" : "/tmp/whereabouts.log",
              "log_level" : "debug"
            },
            "gateway": "",
            "mtu": 1450
        }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: up
spec:
  config: '{
            "cniVersion": "0.3.1",
            "name": "up",
            "type": "macvlan",
            "master": "ens160",
            "ipam": {
              "type": "whereabouts",
              "datastore": "kubernetes",
              "kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
              "range": "172.15.0.0/24",
              "range_start": "172.15.0.11",
              "range_end": "172.15.0.20",
              "log_file" : "/tmp/whereabouts.log",
              "log_level" : "debug"
            },
            "gateway": "",
            "mtu": 1450
        }'
