# Associate this UPF with slice 1/112233
apiVersion: 5g.ibm.com/v1alpha1
kind: Transition
metadata:
  name: smf-addnode-upf2
spec:
  config:
    resourceType: "smfs.v1alpha1.5g.ibm.com"
    resourceNamespace: 5g-core
    resourceName: smf-sample
    transition: AttachNode
    properties:
      nodeId: upf2-sample
      nodeName: upf2-sample
      nodeType: UPF
      sd: "112233"
      sst: "1"
      pools:
        - 10.10.0.0/16
