// +build !ignore_autogenerated

/*
Copyright 2021 IBM.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/5GZORRO/issm-mec-cnmp-5g-operator/api/model"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AffinityInternal) DeepCopyInto(out *AffinityInternal) {
	*out = *in
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(NodeAffinityInternal)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAffinity != nil {
		in, out := &in.PodAffinity, &out.PodAffinity
		*out = new(PodAffinityInternal)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAntiAffinity != nil {
		in, out := &in.PodAntiAffinity, &out.PodAntiAffinity
		*out = new(PodAntiAffinityInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AffinityInternal.
func (in *AffinityInternal) DeepCopy() *AffinityInternal {
	if in == nil {
		return nil
	}
	out := new(AffinityInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Amf) DeepCopyInto(out *Amf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Amf.
func (in *Amf) DeepCopy() *Amf {
	if in == nil {
		return nil
	}
	out := new(Amf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Amf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfConfig) DeepCopyInto(out *AmfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfConfig.
func (in *AmfConfig) DeepCopy() *AmfConfig {
	if in == nil {
		return nil
	}
	out := new(AmfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfInternal) DeepCopyInto(out *AmfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfInternal.
func (in *AmfInternal) DeepCopy() *AmfInternal {
	if in == nil {
		return nil
	}
	out := new(AmfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfList) DeepCopyInto(out *AmfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Amf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfList.
func (in *AmfList) DeepCopy() *AmfList {
	if in == nil {
		return nil
	}
	out := new(AmfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AmfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfOutputs) DeepCopyInto(out *AmfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfOutputs.
func (in *AmfOutputs) DeepCopy() *AmfOutputs {
	if in == nil {
		return nil
	}
	out := new(AmfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfSpec) DeepCopyInto(out *AmfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(AmfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(AmfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfSpec.
func (in *AmfSpec) DeepCopy() *AmfSpec {
	if in == nil {
		return nil
	}
	out := new(AmfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AmfStatus) DeepCopyInto(out *AmfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AmfStatus.
func (in *AmfStatus) DeepCopy() *AmfStatus {
	if in == nil {
		return nil
	}
	out := new(AmfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ausf) DeepCopyInto(out *Ausf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ausf.
func (in *Ausf) DeepCopy() *Ausf {
	if in == nil {
		return nil
	}
	out := new(Ausf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Ausf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfConfig) DeepCopyInto(out *AusfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfConfig.
func (in *AusfConfig) DeepCopy() *AusfConfig {
	if in == nil {
		return nil
	}
	out := new(AusfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfInternal) DeepCopyInto(out *AusfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfInternal.
func (in *AusfInternal) DeepCopy() *AusfInternal {
	if in == nil {
		return nil
	}
	out := new(AusfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfList) DeepCopyInto(out *AusfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Ausf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfList.
func (in *AusfList) DeepCopy() *AusfList {
	if in == nil {
		return nil
	}
	out := new(AusfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AusfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfOutputs) DeepCopyInto(out *AusfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfOutputs.
func (in *AusfOutputs) DeepCopy() *AusfOutputs {
	if in == nil {
		return nil
	}
	out := new(AusfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfSpec) DeepCopyInto(out *AusfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(AusfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(AusfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfSpec.
func (in *AusfSpec) DeepCopy() *AusfSpec {
	if in == nil {
		return nil
	}
	out := new(AusfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AusfStatus) DeepCopyInto(out *AusfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AusfStatus.
func (in *AusfStatus) DeepCopy() *AusfStatus {
	if in == nil {
		return nil
	}
	out := new(AusfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CRStatus) DeepCopyInto(out *CRStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]*metav1.Condition, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(metav1.Condition)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CRStatus.
func (in *CRStatus) DeepCopy() *CRStatus {
	if in == nil {
		return nil
	}
	out := new(CRStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Global) DeepCopyInto(out *Global) {
	*out = *in
	if in.ImagePullPolicy != nil {
		in, out := &in.ImagePullPolicy, &out.ImagePullPolicy
		*out = new(v1.PullPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Global.
func (in *Global) DeepCopy() *Global {
	if in == nil {
		return nil
	}
	out := new(Global)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelectorInternal) DeepCopyInto(out *LabelSelectorInternal) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]LabelSelectorRequirementInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelectorInternal.
func (in *LabelSelectorInternal) DeepCopy() *LabelSelectorInternal {
	if in == nil {
		return nil
	}
	out := new(LabelSelectorInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelSelectorRequirementInternal) DeepCopyInto(out *LabelSelectorRequirementInternal) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelSelectorRequirementInternal.
func (in *LabelSelectorRequirementInternal) DeepCopy() *LabelSelectorRequirementInternal {
	if in == nil {
		return nil
	}
	out := new(LabelSelectorRequirementInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LimitsSpec) DeepCopyInto(out *LimitsSpec) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LimitsSpec.
func (in *LimitsSpec) DeepCopy() *LimitsSpec {
	if in == nil {
		return nil
	}
	out := new(LimitsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Link) DeepCopyInto(out *Link) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Link.
func (in *Link) DeepCopy() *Link {
	if in == nil {
		return nil
	}
	out := new(Link)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LivenessProbeSpec) DeepCopyInto(out *LivenessProbeSpec) {
	*out = *in
	if in.InitialDelaySeconds != nil {
		in, out := &in.InitialDelaySeconds, &out.InitialDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LivenessProbeSpec.
func (in *LivenessProbeSpec) DeepCopy() *LivenessProbeSpec {
	if in == nil {
		return nil
	}
	out := new(LivenessProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Mongo) DeepCopyInto(out *Mongo) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Mongo.
func (in *Mongo) DeepCopy() *Mongo {
	if in == nil {
		return nil
	}
	out := new(Mongo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Mongo) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoConfig) DeepCopyInto(out *MongoConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoConfig.
func (in *MongoConfig) DeepCopy() *MongoConfig {
	if in == nil {
		return nil
	}
	out := new(MongoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoList) DeepCopyInto(out *MongoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Mongo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoList.
func (in *MongoList) DeepCopy() *MongoList {
	if in == nil {
		return nil
	}
	out := new(MongoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MongoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoOutputs) DeepCopyInto(out *MongoOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoOutputs.
func (in *MongoOutputs) DeepCopy() *MongoOutputs {
	if in == nil {
		return nil
	}
	out := new(MongoOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoSpec) DeepCopyInto(out *MongoSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(MongoConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoSpec.
func (in *MongoSpec) DeepCopy() *MongoSpec {
	if in == nil {
		return nil
	}
	out := new(MongoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoStatus) DeepCopyInto(out *MongoStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoStatus.
func (in *MongoStatus) DeepCopy() *MongoStatus {
	if in == nil {
		return nil
	}
	out := new(MongoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N3iwf) DeepCopyInto(out *N3iwf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N3iwf.
func (in *N3iwf) DeepCopy() *N3iwf {
	if in == nil {
		return nil
	}
	out := new(N3iwf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *N3iwf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N3iwfConfig) DeepCopyInto(out *N3iwfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N3iwfConfig.
func (in *N3iwfConfig) DeepCopy() *N3iwfConfig {
	if in == nil {
		return nil
	}
	out := new(N3iwfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N3iwfInternal) DeepCopyInto(out *N3iwfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N3iwfInternal.
func (in *N3iwfInternal) DeepCopy() *N3iwfInternal {
	if in == nil {
		return nil
	}
	out := new(N3iwfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N3iwfList) DeepCopyInto(out *N3iwfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]N3iwf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N3iwfList.
func (in *N3iwfList) DeepCopy() *N3iwfList {
	if in == nil {
		return nil
	}
	out := new(N3iwfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *N3iwfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N3iwfOutputs) DeepCopyInto(out *N3iwfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N3iwfOutputs.
func (in *N3iwfOutputs) DeepCopy() *N3iwfOutputs {
	if in == nil {
		return nil
	}
	out := new(N3iwfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N3iwfSpec) DeepCopyInto(out *N3iwfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(N3iwfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(N3iwfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N3iwfSpec.
func (in *N3iwfSpec) DeepCopy() *N3iwfSpec {
	if in == nil {
		return nil
	}
	out := new(N3iwfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *N3iwfStatus) DeepCopyInto(out *N3iwfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new N3iwfStatus.
func (in *N3iwfStatus) DeepCopy() *N3iwfStatus {
	if in == nil {
		return nil
	}
	out := new(N3iwfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeAffinityInternal) DeepCopyInto(out *NodeAffinityInternal) {
	*out = *in
	if in.RequiredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.RequiredDuringSchedulingIgnoredDuringExecution, &out.RequiredDuringSchedulingIgnoredDuringExecution
		*out = new(NodeSelectorInternal)
		(*in).DeepCopyInto(*out)
	}
	if in.PreferredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.PreferredDuringSchedulingIgnoredDuringExecution, &out.PreferredDuringSchedulingIgnoredDuringExecution
		*out = make([]PreferredSchedulingTermInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeAffinityInternal.
func (in *NodeAffinityInternal) DeepCopy() *NodeAffinityInternal {
	if in == nil {
		return nil
	}
	out := new(NodeAffinityInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorInternal) DeepCopyInto(out *NodeSelectorInternal) {
	*out = *in
	if in.NodeSelectorTerms != nil {
		in, out := &in.NodeSelectorTerms, &out.NodeSelectorTerms
		*out = make([]NodeSelectorTermInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorInternal.
func (in *NodeSelectorInternal) DeepCopy() *NodeSelectorInternal {
	if in == nil {
		return nil
	}
	out := new(NodeSelectorInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorRequirementInternal) DeepCopyInto(out *NodeSelectorRequirementInternal) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorRequirementInternal.
func (in *NodeSelectorRequirementInternal) DeepCopy() *NodeSelectorRequirementInternal {
	if in == nil {
		return nil
	}
	out := new(NodeSelectorRequirementInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSelectorTermInternal) DeepCopyInto(out *NodeSelectorTermInternal) {
	*out = *in
	if in.MatchExpressions != nil {
		in, out := &in.MatchExpressions, &out.MatchExpressions
		*out = make([]NodeSelectorRequirementInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchFields != nil {
		in, out := &in.MatchFields, &out.MatchFields
		*out = make([]NodeSelectorRequirementInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSelectorTermInternal.
func (in *NodeSelectorTermInternal) DeepCopy() *NodeSelectorTermInternal {
	if in == nil {
		return nil
	}
	out := new(NodeSelectorTermInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nrf) DeepCopyInto(out *Nrf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nrf.
func (in *Nrf) DeepCopy() *Nrf {
	if in == nil {
		return nil
	}
	out := new(Nrf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Nrf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrfConfig) DeepCopyInto(out *NrfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrfConfig.
func (in *NrfConfig) DeepCopy() *NrfConfig {
	if in == nil {
		return nil
	}
	out := new(NrfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrfInternal) DeepCopyInto(out *NrfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrfInternal.
func (in *NrfInternal) DeepCopy() *NrfInternal {
	if in == nil {
		return nil
	}
	out := new(NrfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrfList) DeepCopyInto(out *NrfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Nrf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrfList.
func (in *NrfList) DeepCopy() *NrfList {
	if in == nil {
		return nil
	}
	out := new(NrfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NrfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrfOutputs) DeepCopyInto(out *NrfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrfOutputs.
func (in *NrfOutputs) DeepCopy() *NrfOutputs {
	if in == nil {
		return nil
	}
	out := new(NrfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrfSpec) DeepCopyInto(out *NrfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(NrfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(NrfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrfSpec.
func (in *NrfSpec) DeepCopy() *NrfSpec {
	if in == nil {
		return nil
	}
	out := new(NrfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NrfStatus) DeepCopyInto(out *NrfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NrfStatus.
func (in *NrfStatus) DeepCopy() *NrfStatus {
	if in == nil {
		return nil
	}
	out := new(NrfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nssf) DeepCopyInto(out *Nssf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nssf.
func (in *Nssf) DeepCopy() *Nssf {
	if in == nil {
		return nil
	}
	out := new(Nssf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Nssf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NssfConfig) DeepCopyInto(out *NssfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NssfConfig.
func (in *NssfConfig) DeepCopy() *NssfConfig {
	if in == nil {
		return nil
	}
	out := new(NssfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NssfInternal) DeepCopyInto(out *NssfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NssfInternal.
func (in *NssfInternal) DeepCopy() *NssfInternal {
	if in == nil {
		return nil
	}
	out := new(NssfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NssfList) DeepCopyInto(out *NssfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Nssf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NssfList.
func (in *NssfList) DeepCopy() *NssfList {
	if in == nil {
		return nil
	}
	out := new(NssfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NssfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NssfOutputs) DeepCopyInto(out *NssfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NssfOutputs.
func (in *NssfOutputs) DeepCopy() *NssfOutputs {
	if in == nil {
		return nil
	}
	out := new(NssfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NssfSpec) DeepCopyInto(out *NssfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(NssfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(NssfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NssfSpec.
func (in *NssfSpec) DeepCopy() *NssfSpec {
	if in == nil {
		return nil
	}
	out := new(NssfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NssfStatus) DeepCopyInto(out *NssfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NssfStatus.
func (in *NssfStatus) DeepCopy() *NssfStatus {
	if in == nil {
		return nil
	}
	out := new(NssfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pcf) DeepCopyInto(out *Pcf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pcf.
func (in *Pcf) DeepCopy() *Pcf {
	if in == nil {
		return nil
	}
	out := new(Pcf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Pcf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PcfConfig) DeepCopyInto(out *PcfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PcfConfig.
func (in *PcfConfig) DeepCopy() *PcfConfig {
	if in == nil {
		return nil
	}
	out := new(PcfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PcfInternal) DeepCopyInto(out *PcfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PcfInternal.
func (in *PcfInternal) DeepCopy() *PcfInternal {
	if in == nil {
		return nil
	}
	out := new(PcfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PcfList) DeepCopyInto(out *PcfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Pcf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PcfList.
func (in *PcfList) DeepCopy() *PcfList {
	if in == nil {
		return nil
	}
	out := new(PcfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PcfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PcfOutputs) DeepCopyInto(out *PcfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PcfOutputs.
func (in *PcfOutputs) DeepCopy() *PcfOutputs {
	if in == nil {
		return nil
	}
	out := new(PcfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PcfSpec) DeepCopyInto(out *PcfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(PcfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(PcfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PcfSpec.
func (in *PcfSpec) DeepCopy() *PcfSpec {
	if in == nil {
		return nil
	}
	out := new(PcfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PcfStatus) DeepCopyInto(out *PcfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PcfStatus.
func (in *PcfStatus) DeepCopy() *PcfStatus {
	if in == nil {
		return nil
	}
	out := new(PcfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistanceSpec) DeepCopyInto(out *PersistanceSpec) {
	*out = *in
	if in.StorageClassName != nil {
		in, out := &in.StorageClassName, &out.StorageClassName
		*out = new(string)
		**out = **in
	}
	if in.StorageSize != nil {
		in, out := &in.StorageSize, &out.StorageSize
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistanceSpec.
func (in *PersistanceSpec) DeepCopy() *PersistanceSpec {
	if in == nil {
		return nil
	}
	out := new(PersistanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAffinityInternal) DeepCopyInto(out *PodAffinityInternal) {
	*out = *in
	if in.RequiredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.RequiredDuringSchedulingIgnoredDuringExecution, &out.RequiredDuringSchedulingIgnoredDuringExecution
		*out = make([]PodAffinityTermInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreferredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.PreferredDuringSchedulingIgnoredDuringExecution, &out.PreferredDuringSchedulingIgnoredDuringExecution
		*out = make([]WeightedPodAffinityTermInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAffinityInternal.
func (in *PodAffinityInternal) DeepCopy() *PodAffinityInternal {
	if in == nil {
		return nil
	}
	out := new(PodAffinityInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAffinityTermInternal) DeepCopyInto(out *PodAffinityTermInternal) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(LabelSelectorInternal)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAffinityTermInternal.
func (in *PodAffinityTermInternal) DeepCopy() *PodAffinityTermInternal {
	if in == nil {
		return nil
	}
	out := new(PodAffinityTermInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodAntiAffinityInternal) DeepCopyInto(out *PodAntiAffinityInternal) {
	*out = *in
	if in.RequiredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.RequiredDuringSchedulingIgnoredDuringExecution, &out.RequiredDuringSchedulingIgnoredDuringExecution
		*out = make([]PodAffinityTermInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PreferredDuringSchedulingIgnoredDuringExecution != nil {
		in, out := &in.PreferredDuringSchedulingIgnoredDuringExecution, &out.PreferredDuringSchedulingIgnoredDuringExecution
		*out = make([]WeightedPodAffinityTermInternal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodAntiAffinityInternal.
func (in *PodAntiAffinityInternal) DeepCopy() *PodAntiAffinityInternal {
	if in == nil {
		return nil
	}
	out := new(PodAntiAffinityInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodSettingsSpec) DeepCopyInto(out *PodSettingsSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourcesSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodSettingsSpec.
func (in *PodSettingsSpec) DeepCopy() *PodSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(PodSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreferredSchedulingTermInternal) DeepCopyInto(out *PreferredSchedulingTermInternal) {
	*out = *in
	in.Preference.DeepCopyInto(&out.Preference)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreferredSchedulingTermInternal.
func (in *PreferredSchedulingTermInternal) DeepCopy() *PreferredSchedulingTermInternal {
	if in == nil {
		return nil
	}
	out := new(PreferredSchedulingTermInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadinessProbeSpec) DeepCopyInto(out *ReadinessProbeSpec) {
	*out = *in
	if in.InitialDelaySeconds != nil {
		in, out := &in.InitialDelaySeconds, &out.InitialDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SuccessThreshold != nil {
		in, out := &in.SuccessThreshold, &out.SuccessThreshold
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadinessProbeSpec.
func (in *ReadinessProbeSpec) DeepCopy() *ReadinessProbeSpec {
	if in == nil {
		return nil
	}
	out := new(ReadinessProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequestsSpec) DeepCopyInto(out *RequestsSpec) {
	*out = *in
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(string)
		**out = **in
	}
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequestsSpec.
func (in *RequestsSpec) DeepCopy() *RequestsSpec {
	if in == nil {
		return nil
	}
	out := new(RequestsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourcesSpec) DeepCopyInto(out *ResourcesSpec) {
	*out = *in
	in.Requests.DeepCopyInto(&out.Requests)
	in.Limits.DeepCopyInto(&out.Limits)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourcesSpec.
func (in *ResourcesSpec) DeepCopy() *ResourcesSpec {
	if in == nil {
		return nil
	}
	out := new(ResourcesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Smf) DeepCopyInto(out *Smf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Smf.
func (in *Smf) DeepCopy() *Smf {
	if in == nil {
		return nil
	}
	out := new(Smf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Smf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfConfig) DeepCopyInto(out *SmfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]UpNode, len(*in))
		copy(*out, *in)
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]Link, len(*in))
		copy(*out, *in)
	}
	in.UEList.DeepCopyInto(&out.UEList)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfConfig.
func (in *SmfConfig) DeepCopy() *SmfConfig {
	if in == nil {
		return nil
	}
	out := new(SmfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfInternal) DeepCopyInto(out *SmfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfInternal.
func (in *SmfInternal) DeepCopy() *SmfInternal {
	if in == nil {
		return nil
	}
	out := new(SmfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfList) DeepCopyInto(out *SmfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Smf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfList.
func (in *SmfList) DeepCopy() *SmfList {
	if in == nil {
		return nil
	}
	out := new(SmfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfOutputs) DeepCopyInto(out *SmfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfOutputs.
func (in *SmfOutputs) DeepCopy() *SmfOutputs {
	if in == nil {
		return nil
	}
	out := new(SmfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfSpec) DeepCopyInto(out *SmfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(SmfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(SmfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfSpec.
func (in *SmfSpec) DeepCopy() *SmfSpec {
	if in == nil {
		return nil
	}
	out := new(SmfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmfStatus) DeepCopyInto(out *SmfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmfStatus.
func (in *SmfStatus) DeepCopy() *SmfStatus {
	if in == nil {
		return nil
	}
	out := new(SmfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subscriber) DeepCopyInto(out *Subscriber) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subscriber.
func (in *Subscriber) DeepCopy() *Subscriber {
	if in == nil {
		return nil
	}
	out := new(Subscriber)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Subscriber) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriberConfig) DeepCopyInto(out *SubscriberConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriberConfig.
func (in *SubscriberConfig) DeepCopy() *SubscriberConfig {
	if in == nil {
		return nil
	}
	out := new(SubscriberConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriberInternal) DeepCopyInto(out *SubscriberInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriberInternal.
func (in *SubscriberInternal) DeepCopy() *SubscriberInternal {
	if in == nil {
		return nil
	}
	out := new(SubscriberInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriberList) DeepCopyInto(out *SubscriberList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Subscriber, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriberList.
func (in *SubscriberList) DeepCopy() *SubscriberList {
	if in == nil {
		return nil
	}
	out := new(SubscriberList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubscriberList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriberOutputs) DeepCopyInto(out *SubscriberOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriberOutputs.
func (in *SubscriberOutputs) DeepCopy() *SubscriberOutputs {
	if in == nil {
		return nil
	}
	out := new(SubscriberOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriberSpec) DeepCopyInto(out *SubscriberSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(SubscriberConfig)
		**out = **in
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(SubscriberInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriberSpec.
func (in *SubscriberSpec) DeepCopy() *SubscriberSpec {
	if in == nil {
		return nil
	}
	out := new(SubscriberSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriberStatus) DeepCopyInto(out *SubscriberStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriberStatus.
func (in *SubscriberStatus) DeepCopy() *SubscriberStatus {
	if in == nil {
		return nil
	}
	out := new(SubscriberStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transition) DeepCopyInto(out *Transition) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transition.
func (in *Transition) DeepCopy() *Transition {
	if in == nil {
		return nil
	}
	out := new(Transition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Transition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionConfig) DeepCopyInto(out *TransitionConfig) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make(model.Properties, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionConfig.
func (in *TransitionConfig) DeepCopy() *TransitionConfig {
	if in == nil {
		return nil
	}
	out := new(TransitionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionList) DeepCopyInto(out *TransitionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Transition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionList.
func (in *TransitionList) DeepCopy() *TransitionList {
	if in == nil {
		return nil
	}
	out := new(TransitionList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TransitionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionSpec) DeepCopyInto(out *TransitionSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(TransitionConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionSpec.
func (in *TransitionSpec) DeepCopy() *TransitionSpec {
	if in == nil {
		return nil
	}
	out := new(TransitionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransitionStatus) DeepCopyInto(out *TransitionStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransitionStatus.
func (in *TransitionStatus) DeepCopy() *TransitionStatus {
	if in == nil {
		return nil
	}
	out := new(TransitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UE) DeepCopyInto(out *UE) {
	*out = *in
	if in.UPFPath != nil {
		in, out := &in.UPFPath, &out.UPFPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UE.
func (in *UE) DeepCopy() *UE {
	if in == nil {
		return nil
	}
	out := new(UE)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UEList) DeepCopyInto(out *UEList) {
	*out = *in
	if in.UES != nil {
		in, out := &in.UES, &out.UES
		*out = make([]UE, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UEList.
func (in *UEList) DeepCopy() *UEList {
	if in == nil {
		return nil
	}
	out := new(UEList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Udm) DeepCopyInto(out *Udm) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Udm.
func (in *Udm) DeepCopy() *Udm {
	if in == nil {
		return nil
	}
	out := new(Udm)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Udm) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdmConfig) DeepCopyInto(out *UdmConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdmConfig.
func (in *UdmConfig) DeepCopy() *UdmConfig {
	if in == nil {
		return nil
	}
	out := new(UdmConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdmInternal) DeepCopyInto(out *UdmInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdmInternal.
func (in *UdmInternal) DeepCopy() *UdmInternal {
	if in == nil {
		return nil
	}
	out := new(UdmInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdmList) DeepCopyInto(out *UdmList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Udm, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdmList.
func (in *UdmList) DeepCopy() *UdmList {
	if in == nil {
		return nil
	}
	out := new(UdmList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UdmList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdmOutputs) DeepCopyInto(out *UdmOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdmOutputs.
func (in *UdmOutputs) DeepCopy() *UdmOutputs {
	if in == nil {
		return nil
	}
	out := new(UdmOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdmSpec) DeepCopyInto(out *UdmSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(UdmConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(UdmInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdmSpec.
func (in *UdmSpec) DeepCopy() *UdmSpec {
	if in == nil {
		return nil
	}
	out := new(UdmSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdmStatus) DeepCopyInto(out *UdmStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdmStatus.
func (in *UdmStatus) DeepCopy() *UdmStatus {
	if in == nil {
		return nil
	}
	out := new(UdmStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Udr) DeepCopyInto(out *Udr) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Udr.
func (in *Udr) DeepCopy() *Udr {
	if in == nil {
		return nil
	}
	out := new(Udr)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Udr) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdrConfig) DeepCopyInto(out *UdrConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdrConfig.
func (in *UdrConfig) DeepCopy() *UdrConfig {
	if in == nil {
		return nil
	}
	out := new(UdrConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdrInternal) DeepCopyInto(out *UdrInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdrInternal.
func (in *UdrInternal) DeepCopy() *UdrInternal {
	if in == nil {
		return nil
	}
	out := new(UdrInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdrList) DeepCopyInto(out *UdrList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Udr, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdrList.
func (in *UdrList) DeepCopy() *UdrList {
	if in == nil {
		return nil
	}
	out := new(UdrList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UdrList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdrOutputs) DeepCopyInto(out *UdrOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdrOutputs.
func (in *UdrOutputs) DeepCopy() *UdrOutputs {
	if in == nil {
		return nil
	}
	out := new(UdrOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdrSpec) DeepCopyInto(out *UdrSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(UdrConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(UdrInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdrSpec.
func (in *UdrSpec) DeepCopy() *UdrSpec {
	if in == nil {
		return nil
	}
	out := new(UdrSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UdrStatus) DeepCopyInto(out *UdrStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UdrStatus.
func (in *UdrStatus) DeepCopy() *UdrStatus {
	if in == nil {
		return nil
	}
	out := new(UdrStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpNode) DeepCopyInto(out *UpNode) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpNode.
func (in *UpNode) DeepCopy() *UpNode {
	if in == nil {
		return nil
	}
	out := new(UpNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Upf) DeepCopyInto(out *Upf) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Upf.
func (in *Upf) DeepCopy() *Upf {
	if in == nil {
		return nil
	}
	out := new(Upf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Upf) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfConfig) DeepCopyInto(out *UpfConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfConfig.
func (in *UpfConfig) DeepCopy() *UpfConfig {
	if in == nil {
		return nil
	}
	out := new(UpfConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfInternal) DeepCopyInto(out *UpfInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfInternal.
func (in *UpfInternal) DeepCopy() *UpfInternal {
	if in == nil {
		return nil
	}
	out := new(UpfInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfList) DeepCopyInto(out *UpfList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Upf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfList.
func (in *UpfList) DeepCopy() *UpfList {
	if in == nil {
		return nil
	}
	out := new(UpfList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UpfList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfOutputs) DeepCopyInto(out *UpfOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfOutputs.
func (in *UpfOutputs) DeepCopy() *UpfOutputs {
	if in == nil {
		return nil
	}
	out := new(UpfOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfSpec) DeepCopyInto(out *UpfSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(UpfConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(UpfInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfSpec.
func (in *UpfSpec) DeepCopy() *UpfSpec {
	if in == nil {
		return nil
	}
	out := new(UpfSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpfStatus) DeepCopyInto(out *UpfStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpfStatus.
func (in *UpfStatus) DeepCopy() *UpfStatus {
	if in == nil {
		return nil
	}
	out := new(UpfStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Webconsole) DeepCopyInto(out *Webconsole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Webconsole.
func (in *Webconsole) DeepCopy() *Webconsole {
	if in == nil {
		return nil
	}
	out := new(Webconsole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Webconsole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleConfig) DeepCopyInto(out *WebconsoleConfig) {
	*out = *in
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(PodSettingsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleConfig.
func (in *WebconsoleConfig) DeepCopy() *WebconsoleConfig {
	if in == nil {
		return nil
	}
	out := new(WebconsoleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleInternal) DeepCopyInto(out *WebconsoleInternal) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleInternal.
func (in *WebconsoleInternal) DeepCopy() *WebconsoleInternal {
	if in == nil {
		return nil
	}
	out := new(WebconsoleInternal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleList) DeepCopyInto(out *WebconsoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Webconsole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleList.
func (in *WebconsoleList) DeepCopy() *WebconsoleList {
	if in == nil {
		return nil
	}
	out := new(WebconsoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WebconsoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleOutputs) DeepCopyInto(out *WebconsoleOutputs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleOutputs.
func (in *WebconsoleOutputs) DeepCopy() *WebconsoleOutputs {
	if in == nil {
		return nil
	}
	out := new(WebconsoleOutputs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleSpec) DeepCopyInto(out *WebconsoleSpec) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(WebconsoleConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Internal != nil {
		in, out := &in.Internal, &out.Internal
		*out = new(WebconsoleInternal)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleSpec.
func (in *WebconsoleSpec) DeepCopy() *WebconsoleSpec {
	if in == nil {
		return nil
	}
	out := new(WebconsoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebconsoleStatus) DeepCopyInto(out *WebconsoleStatus) {
	*out = *in
	in.CRStatus.DeepCopyInto(&out.CRStatus)
	out.Outputs = in.Outputs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebconsoleStatus.
func (in *WebconsoleStatus) DeepCopy() *WebconsoleStatus {
	if in == nil {
		return nil
	}
	out := new(WebconsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WeightedPodAffinityTermInternal) DeepCopyInto(out *WeightedPodAffinityTermInternal) {
	*out = *in
	in.PodAffinityTerm.DeepCopyInto(&out.PodAffinityTerm)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WeightedPodAffinityTermInternal.
func (in *WeightedPodAffinityTermInternal) DeepCopy() *WeightedPodAffinityTermInternal {
	if in == nil {
		return nil
	}
	out := new(WeightedPodAffinityTermInternal)
	in.DeepCopyInto(out)
	return out
}
