apiVersion: 5g.ibm.com/v1alpha1
kind: Transition
metadata:
  # need to disambiguate between different operations from different sources in the assembly i.e. in this case upf1 and upfb
  name: "{{ system_properties.resourceSubdomain }}-{{ DestinationIP }}-addueroute"
spec:
  config:
    resourceType: "smfs.v1alpha1.5g.ibm.com"
    resourceNamespace: "{{ deployment_location.properties.defaultObjectNamespace }}"
    resourceName: "{{ system_properties.resourceSubdomain }}"
    transition: "AddUERoute"
    properties:
      SUPI: ""{{ SUPI }}"
      AN: "{{ AN }}"
      DestinationIP: "{{ DestinationIP }}"
      DestinationPort: "{{ DestinationPort }}"
      UPFPath: "{{ UPFPath }}"
