apiVersion: 5g.ibm.com/v1alpha1
kind: Mongo
metadata:
  name: "{{ system_properties.resourceSubdomain }}"
  namespace: "{{ deployment_location.properties['defaultObjectNamespace'] }}"
spec:
  config:
    podSettings:
      resources:
        requests:
          memory: "400Mi"
          cpu: "0.2"
        limits:
          memory: "400Mi"
          cpu: "0.2"
    image: "{{ registry_ip }}:{{ registry_port }}/mongo:latest"