# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/5g.ibm.com_amfs.yaml
- bases/5g.ibm.com_nrves.yaml
- bases/5g.ibm.com_mongoes.yaml
- bases/5g.ibm.com_udrs.yaml
- bases/5g.ibm.com_upfs.yaml
- bases/5g.ibm.com_udms.yaml
- bases/5g.ibm.com_smfs.yaml
- bases/5g.ibm.com_pcfs.yaml
- bases/5g.ibm.com_nssfs.yaml
- bases/5g.ibm.com_n3iwfs.yaml
- bases/5g.ibm.com_ausfs.yaml
- bases/5g.ibm.com_subscribers.yaml
- bases/5g.ibm.com_webconsoles.yaml
- bases/5g.ibm.com_transitions.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_amfs.yaml
#- patches/webhook_in_nrves.yaml
#- patches/webhook_in_mongoes.yaml
#- patches/webhook_in_udrs.yaml
#- patches/webhook_in_upfs.yaml
#- patches/webhook_in_udms.yaml
#- patches/webhook_in_smfs.yaml
#- patches/webhook_in_pcfs.yaml
#- patches/webhook_in_nssfs.yaml
#- patches/webhook_in_n3iwfs.yaml
#- patches/webhook_in_ausfs.yaml
#- patches/webhook_in_subscribers.yaml
#- patches/webhook_in_webconsoles.yaml
#- patches/webhook_in_transitions.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_amfs.yaml
#- patches/cainjection_in_nrves.yaml
#- patches/cainjection_in_mongoes.yaml
#- patches/cainjection_in_udrs.yaml
#- patches/cainjection_in_upfs.yaml
#- patches/cainjection_in_udms.yaml
#- patches/cainjection_in_smfs.yaml
#- patches/cainjection_in_pcfs.yaml
#- patches/cainjection_in_nssfs.yaml
#- patches/cainjection_in_n3iwfs.yaml
#- patches/cainjection_in_ausfs.yaml
#- patches/cainjection_in_subscribers.yaml
#- patches/cainjection_in_webconsoles.yaml
#- patches/cainjection_in_transitions.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
